const icons = {
  logo01: require("./napatsorn_logo_01.svg"),
  logo02: require("./napatsorn_logo_02.svg"),
  list: require("./list.svg"),
  upload: require("./upload.svg"),
  logout: require("./logout.svg"),
  eyeOpen: require("./eye-open.svg"),
  eyeClose: require("./eye-close.svg"),
  addList: require("./add-list.svg"),
  person: require("./person.svg"),
  uploadgrey: require("./uploadgrey.svg"),
  pen: require("./pen.svg"),
  lessThan: require("./less-than.svg"),
  moreThan: require("./more-than.svg"),
  excelIcon: require("./excel.svg"),
  information: require("./Vector.svg"),
  plus: require("./plus.svg"),
  noResultFound: require("./No Result Found illustration.svg"),
  back: require("./back.svg"),
  gear: require("./gear.svg"),
  trash: require("./trash.svg"),
  warning: require("./warning.svg"),
  error: require("./error.svg"),
  hamburger: require("./hamburger.svg"),
  user: require("./user.svg"),
};
export default icons;
